apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-lucas-oct2-1-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/chatbot-lucas-oct2-1/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/chatbot-lucas-oct2-1-gitops.git
    targetRevision: main
  destination:
    server: https://api.mfaisal-oct2.devcluster.openshift.com:6443
    namespace: chatbot-october2-test-1
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
